# ============================================================================
# SNAKEMAKE RULES: PIPELINE INFO (Metadata Generation)
# FASE 2: Generate execution metadata for reproducibility
# ============================================================================

# Load configuration
configfile: "config/config.yaml"

# ============================================================================
# COMMON PATHS
# ============================================================================

OUTPUT_PIPELINE_INFO = "results/pipeline_info"
SCRIPTS_UTILS = config["paths"]["snakemake_dir"] + "/" + config["paths"]["scripts"]["utils"]
CONFIG_FILE = config["paths"]["snakemake_dir"] + "/config/config.yaml"

# ============================================================================
# RULE: Generate Pipeline Info (execution_info.yaml, software_versions.yml, etc.)
# ============================================================================

rule generate_pipeline_info:
    input:
        config = CONFIG_FILE
        # Note: We don't require all steps to be complete
        # This allows generating metadata even for partial runs
    output:
        execution_info = OUTPUT_PIPELINE_INFO + "/execution_info.yaml",
        software_versions = OUTPUT_PIPELINE_INFO + "/software_versions.yml",
        config_used = OUTPUT_PIPELINE_INFO + "/config_used.yaml",
        provenance = OUTPUT_PIPELINE_INFO + "/provenance.json"
    params:
        config_file = CONFIG_FILE,
        output_dir = OUTPUT_PIPELINE_INFO,
        snakemake_dir = config["paths"]["snakemake_dir"]
    log:
        OUTPUT_PIPELINE_INFO + "/generate_pipeline_info.log"
    script:
        SCRIPTS_UTILS + "/generate_pipeline_info.R"

# ============================================================================
# RULE: Snakemake Execution Report (automatic - generated by Snakemake)
# ============================================================================
# Note: Snakemake automatically generates execution_report.html
# This rule ensures the pipeline_info directory exists before Snakemake writes to it

rule prepare_pipeline_info_dir:
    output:
        directory(OUTPUT_PIPELINE_INFO)
    shell:
        "mkdir -p {output} && touch {output}/.gitkeep"

